//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVENT_VER5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROMOTE_L
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROMOTE_L()
        {
            this.LOCATION = new HashSet<LOCATION>();
        }
    
        public short PROMOTE_ID { get; set; }
        public Nullable<int> BUDGETS { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<short> MEMBER_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOCATION> LOCATION { get; set; }
        public virtual MEMBER MEMBER { get; set; }
    }
}
