//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVENT_VER5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROMOTE_E
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROMOTE_E()
        {
            this.EVENT = new HashSet<EVENT>();
        }
    
        public short PROMOTE_ID { get; set; }
        public Nullable<int> BUDGETS { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<short> MEMBER_ID { get; set; }
        public string TARGET_GENDER { get; set; }
        public Nullable<byte> TARGET_MIN_AGE { get; set; }
        public Nullable<byte> TARGET_MAX_AGE { get; set; }
        public string TARGET_INTEREST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVENT> EVENT { get; set; }
        public virtual MEMBER MEMBER { get; set; }
    }
}
